version: '3'
volumes:
  challenge_pgdata:
services:
  volumes-provisioner:
    image: hasnat/volumes-provisioner
    environment:
      PROVISION_DIRECTORIES: "0:0:0777:/venmo_input;0:0:0777:/venmo_output;"
    volumes:
      - ./venmo_input:/venmo_input
      - ./venmo_output:/venmo_output
    network_mode: none
  nifi:
    hostname: challenge_nifi
    container_name: challenge_nifi
    build: ./nifi
    # image: apache/nifi:latest
    ports:
      - "8080:8080"
      - "8443:8443"
      - "10000:10000"
    volumes:
      - ./venmo_input:/venmo_input
      - ./venmo_output:/venmo_output
  zookeeper:
    hostname: challenge_zookeeper
    container_name: challenge_zookeeper
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  postgres:
    hostname: challenge_postgres
    container_name: challenge_postgres
    build: ./postgres
    ports:
      - "5432:5432"
    volumes:
      - challenge_pgdata:/var/lib/postgresql/data
  redis:
    hostname: challenge_redis
    container_name: challenge_redis
    image: redis:5.0.6
    ports:
      - "6379:6379"
